name: Release

on:
  release:
    types: [published]

jobs:
  build-and-upload-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Setup Theme ZIP file
        id: setup
        run: |
          COMPONENT='theme_suap'
          VERSION="${{ github.ref_name }}"
          echo "ZIPFILE=moodle-${COMPONENT}-${VERSION}.zip" >> $GITHUB_ENV

      - name: Build Theme ZIP file
        run: |
          php ./cli/buildthemezip.php moodle-theme_suap ${{ env.ZIPFILE }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ZIPFILE }}
          asset_name: ${{ env.ZIPFILE }}
          asset_content_type: application/zip
