name: Release

on:
  release:
    types: [published]

jobs:
  build-and-upload-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theme ZIP file
        run: |
          COMPONENT='theme_suap'
          VERSION='${{ github.event.release.tag_name }}'
          ZIPFILE="moodle-${COMPONENT}-${VERSION}.zip"

          echo $ZIPFILE

          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV

          mkdir -p build/suap

          rsync -a ./ build/suap/ \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "build" \
            --exclude "*.zip"

          cd build
          zip -r "../${ZIPFILE}" "suap"

          pwd
          ls -lha ..

      - name: Debug generated files
        run: |
          echo "ZIPFILE=${ZIPFILE}"
          ls -lah .
          unzip -l "${ZIPFILE}" | head -n 40

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" "${ZIPFILE}" --clobber

